title: SmartRain
email: info@pikobytes.de
description: >- # this means to ignore newlines until "baseurl:"
 SmartRain ist ein Projekt welches den Aufbau eines Monitoring-Netzwerks für lokale Niederschlagsmessungen
 zum Ziel hat. Das Projekt wird zusammen von der in der Landeshauptstadt Dresden, der TU Dresden, der PIKOBYTES
 GmbH und der Elco Industrie Automation GmbH durchgeführt.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://smart-rain.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
